Add custom CodeQL action (#567)
- This custom action doesn't run integration tests as part of the build
step as opposed to the default CodeQL workflow setup using Github.
This should reduce our PR build times significantly.
- Updates Makefile as building collector was causing the following
  error: `go: cannot write multiple packages to non-directory
bin/collector`

Co-authored-by: Tanay Kothari <tanaykothari@microsoft.com>